name: Withdraw
main: UniversalRemote\Withdraw
version: "1.0"
api: [3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.1]

commands:
 withdraw:
  permission: withdraw.cmd
  description: Withdraw

permissions:
 withdraw.cmd:
  default: true
  description: Withdraw command.
